packages:
  - 'tools/*'
  - 'packages/*'

catalog:
  "@stylistic/eslint-plugin": 5.2.3
  "@stylistic/eslint-plugin-js": 4.4.1
  "@eslint/js": 9.32.0
  "@types/node": 22.17.0
  "@typescript-eslint/utils": 8.38.0
  concurrently: 9.2.0
  dependency-cruiser: 17.0.1
  eslint: 9.32.0
  eslint-plugin-simple-import-sort: 12.1.1
  globals: 16.3.0
  jiti: 2.5.1
  typescript: 5.8.3
  typescript-eslint: 8.38.0
  vitest: 3.2.4
