packages:
  - 'tools/*'
  - 'packages/*'

catalog:
  "@stylistic/eslint-plugin": 4.0.1
  "@stylistic/eslint-plugin-js": 4.0.1
  "@eslint/js": 9.21.0
  "@types/node": 22.13.1
  "@typescript-eslint/utils": 8.24.1
  concurrently: 9.1.2
  dependency-cruiser: 16.9.0
  eslint: 9.21.0
  eslint-plugin-simple-import-sort: 12.1.1
  globals: 16.0.0
  jiti: 2.4.2
  typescript: 5.6.3
  typescript-eslint: 8.24.1
  vitest: 3.0.6
