packages:
  - 'tools/*'
  - 'packages/*'

catalog:
  "@stylistic/eslint-plugin": 5.7.1
  "@stylistic/eslint-plugin-js": 4.4.1
  "@eslint/js": 10.0.1
  "@types/node": 24.10.13
  "@typescript-eslint/utils": 8.55.0
  concurrently: 9.2.1
  dependency-cruiser: 17.3.7
  eslint: 10.0.1
  eslint-plugin-simple-import-sort: 12.1.1
  globals: 17.3.0
  jiti: 2.6.1
  typescript: 5.9.3
  typescript-eslint: 8.55.0
  vitest: 3.2.4
