packages:
  - 'tools/*'
  - 'packages/*'

catalog:
  "@stylistic/eslint-plugin": 5.7.1
  "@stylistic/eslint-plugin-js": 4.4.1
  "@eslint/js": 9.39.2
  "@types/node": 24.10.9
  "@typescript-eslint/utils": 8.53.1
  concurrently: 9.2.1
  dependency-cruiser: 17.3.7
  eslint: 9.39.2
  eslint-plugin-simple-import-sort: 12.1.1
  globals: 16.5.0
  jiti: 2.6.1
  typescript: 5.9.3
  typescript-eslint: 8.53.1
  vitest: 3.2.4
