packages:
  - 'tools/*'
  - 'packages/*'

catalog:
  "@stylistic/eslint-plugin": 5.4.0
  "@stylistic/eslint-plugin-js": 4.4.1
  "@eslint/js": 9.36.0
  "@types/node": 22.18.6
  "@typescript-eslint/utils": 8.44.1
  concurrently: 9.2.1
  dependency-cruiser: 17.0.1
  eslint: 9.36.0
  eslint-plugin-simple-import-sort: 12.1.1
  globals: 16.4.0
  jiti: 2.6.0
  typescript: 5.8.3
  typescript-eslint: 8.44.1
  vitest: 3.2.4
