packages:
  - 'tools/*'
  - 'packages/*'

catalog:
  "@stylistic/eslint-plugin": 4.4.1
  "@stylistic/eslint-plugin-js": 4.4.1
  "@eslint/js": 9.29.0
  "@types/node": 22.15.32
  "@typescript-eslint/utils": 8.34.1
  concurrently: 9.1.2
  dependency-cruiser: 16.10.3
  eslint: 9.29.0
  eslint-plugin-simple-import-sort: 12.1.1
  globals: 16.2.0
  jiti: 2.4.2
  typescript: 5.8.3
  typescript-eslint: 8.34.1
  vitest: 3.2.4
