packages:
  - 'tools/*'
  - 'packages/*'

catalog:
  "@stylistic/eslint-plugin": 4.2.0
  "@stylistic/eslint-plugin-js": 4.2.0
  "@eslint/js": 9.23.0
  "@types/node": 22.13.14
  "@typescript-eslint/utils": 8.28.0
  concurrently: 9.1.2
  dependency-cruiser: 16.10.0
  eslint: 9.23.0
  eslint-plugin-simple-import-sort: 12.1.1
  globals: 16.0.0
  jiti: 2.4.2
  typescript: 5.6.3
  typescript-eslint: 8.28.0
  vitest: 3.1.1
