packages:
  - 'tools/*'
  - 'packages/*'

catalog:
  "@stylistic/eslint-plugin": 3.0.0
  "@stylistic/eslint-plugin-js": 3.0.0
  "@types/eslint__js": 8.42.3
  "@types/node": 22.10.7
  "@typescript-eslint/utils": 8.21.0
  concurrently: 9.1.2
  dependency-cruiser: 16.9.0
  eslint: 9.19.0
  globals: 15.14.0
  jiti: 2.4.2
  typescript: 5.6.3
  typescript-eslint: 8.21.0
  vitest: 2.1.8
