packages:
  - 'tools/*'
  - 'packages/*'

catalog:
  "@stylistic/eslint-plugin": 5.1.0
  "@stylistic/eslint-plugin-js": 4.4.1
  "@eslint/js": 9.30.1
  "@types/node": 22.16.0
  "@typescript-eslint/utils": 8.35.1
  concurrently: 9.2.0
  dependency-cruiser: 16.10.4
  eslint: 9.30.1
  eslint-plugin-simple-import-sort: 12.1.1
  globals: 16.3.0
  jiti: 2.4.2
  typescript: 5.8.3
  typescript-eslint: 8.35.1
  vitest: 3.2.4
