packages:
  - 'tools/*'
  - 'packages/*'

catalog:
  "@stylistic/eslint-plugin": 5.3.1
  "@stylistic/eslint-plugin-js": 4.4.1
  "@eslint/js": 9.35.0
  "@types/node": 22.18.1
  "@typescript-eslint/utils": 8.43.0
  concurrently: 9.2.1
  dependency-cruiser: 17.0.1
  eslint: 9.35.0
  eslint-plugin-simple-import-sort: 12.1.1
  globals: 16.3.0
  jiti: 2.5.1
  typescript: 5.8.3
  typescript-eslint: 8.43.0
  vitest: 3.2.4
