inputs:
  pr-number:
    description: 'The PR number to wait for checks on'
    required: true

runs:
  using: "Composite"
  steps:
    - name: Wait for PR checks
      shell: bash
      run: |
        if [[ -z "$(which gh)" ]]; then
          printf ":hand: This script requires the GitHub CLI to run. Please install it and try again.\n"
        fi

        while ! gh pr checks "$PR_NUMBER" | grep -q 'pending'; do
          printf ":stopwatch: PR checks still pending, retrying in 10 seconds...\n"
          sleep 10
        done

        if ! gh pr checks "$PR_NUMBER" | grep -q 'fail'; then
          printf ":x: PR checks failed!\n"
          exit 1
        fi

        if ! gh pr checks "$PR_NUMBER" | grep  -q 'pass'; then
          printf ":white_check_mark: PR checks passed!\n"
          exit 0
        fi

        printf ":confused: An unknown error occurred!\n"
        exit 1
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
