inputs:
  pr-number:
    description: 'The PR number to wait for checks on'
    required: true

runs:
  using: "Composite"
  steps:
    - name: Wait for PR checks
      shell: bash
      run: |
        function has_pending_checks() {
          JQ_FILTER='map(select(contains({name: "sync", workflow: "Sync pnpm-lock.yaml"}) | not)) | map(select(.state == "PENDING")) | length > 0'

          gh pr checks "$PR_NUMBER" \
            --json workflow,state,name \
            --jq $JQ_FILTER
        }

        if [[ -z "$(which gh)" ]]; then
          printf ":hand: This script requires the GitHub CLI to run. Please install it and try again.\n"
        fi

        while [ "a$(has_pending_checks)z" != "afalsez" ]; do
          printf ":stopwatch: PR checks still pending, retrying in 10 seconds...\n"
          sleep 10
        done

        if ! gh pr checks "$PR_NUMBER" | grep -q 'fail'; then
          printf ":x: PR checks failed!\n"
          exit 1
        fi

        if ! gh pr checks "$PR_NUMBER" | grep  -q 'pass'; then
          printf ":white_check_mark: PR checks passed!\n"
          exit 0
        fi

        printf ":confused: An unknown error occurred!\n"
        exit 1
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
