name: "Setup node and pnpm"
description: "This action sets up the Node.js and PNPM versions based on the package.json file."
runs:
  using: "composite"
  steps:
    - name: Set node & pnpm version
      shell: bash
      run: |
        node_version=$(cat package.json | jq -r .engines.node)
        pnpm_version=$(cat package.json | jq -r .packageManager | awk '{ gsub(/^[^@]+@/, ""); print }')
        echo "NODE_VERSION=${node_version}" >> $GITHUB_ENV
        echo "PNPM_VERSION=${pnpm_version}" >> $GITHUB_ENV

    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: ${{ env.PNPM_VERSION }}

    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "pnpm"
