name: "Setup node and pnpm"
description: "This action sets up the Node.js and PNPM versions based on the package.json file."
runs:
  using: "composite"
  steps:
    - name: Set node & pnpm version
      shell: bash
      run: |
        node_version=$(cat package.json | jq -r .engines.node)
        pnpm_version=$(cat package.json | jq -r .packageManager | awk '{ gsub(/^[^@]+@/, ""); print }')
        echo "NODE_VERSION=${node_version}" >> $GITHUB_ENV
        echo "PNPM_VERSION=${pnpm_version}" >> $GITHUB_ENV

    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        version: ${{ env.PNPM_VERSION }}

    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "pnpm"
