name: Auto Approve Bot

on:
  issue_comment:
    types: [created]

env:
  BACKEND_DIRECTORY: packages/backend

jobs:
  approve:
    name: Auto Approve
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/approve' && github.event.pull_request.user.login == env.GITHUB_REPOSITORY_OWNER }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      NUMBER: ${{ github.event.number }}
    steps:
      - name: Put a reaction to the comment
        run: gh api graphql --silent --raw-field query="mutation AddReaction {addReaction(input:{subjectId:\"$NODE_ID\",content:+1}){reaction{content}subject{id}}}"
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
          NODE_ID: ${{ github.event.comment.node_id }}

      - name: Approve Pull Request
        run: |
          gh pr review $NUMBER --approve
        env:
          REVIEWER: ${{ github.event.requested_reviewer.login }}
