name: Auto Approve Bot

on:
  issue_comment:
    types: [created]

jobs:
  approve:
    name: Auto Approve
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/approve' && github.event.issue.user.login == github.event.repository.owner.login }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
      issues: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Put a reaction to the comment
        run: |
          gh api graphql \
            --silent \
            --raw-field \
            query="mutation AddReaction {addReaction(input:{subjectId:\"$NODE_ID\",content:THUMBS_UP}){reaction{content}subject{id}}}"
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
          NODE_ID: ${{ github.event.comment.node_id }}

      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string

      - name: Approve Pull Request
        run: |
          gh pr review $NUMBER --approve
        env:
          NUMBER: ${{ steps.get_issue_number.outputs.result }}
