name: Pull Request for Frontend

on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  FRONTEND_DIRECTORY: packages/frontend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set node version
        run: |
          node_version=$(cat package.json | jq -r .engines.node)
          echo "NODE_VERSION=${node_version}" >> $GITHUB_ENV
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set pnpm version
        shell: bash
        run: |
          pnpm_version=$(cat package.json | jq -r .engines.pnpm)
          echo "PNPM_VERSION=${pnpm_version}" >> $GITHUB_ENV
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Cache node modules
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: pnpm i

      - name: Lint Check
        run: |
          # create auto-generated files before linting because linter requires them to check
          pnpm -C ${{ env.FRONTEND_DIRECTORY }} exec run-p gen-app-info license
          pnpm -C ${{ env.FRONTEND_DIRECTORY }} exec run-p "circular" "lint"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set node version
        run: |
          node_version=$(cat package.json | jq -r .engines.node)
          echo "NODE_VERSION=${node_version}" >> $GITHUB_ENV
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set pnpm version
        shell: bash
        run: |
          pnpm_version=$(cat package.json | jq -r .engines.pnpm)
          echo "PNPM_VERSION=${pnpm_version}" >> $GITHUB_ENV
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Cache node modules
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm -C ${{ env.FRONTEND_DIRECTORY }} build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set node version
        run: |
          node_version=$(cat package.json | jq -r .engines.node)
          echo "NODE_VERSION=${node_version}" >> $GITHUB_ENV
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set pnpm version
        shell: bash
        run: |
          pnpm_version=$(cat package.json | jq -r .engines.pnpm)
          echo "PNPM_VERSION=${pnpm_version}" >> $GITHUB_ENV
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Cache node modules
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: pnpm i

      - name: Run Unit Test
        run: pnpm -C ${{ env.FRONTEND_DIRECTORY }} test
